### ISSUE TITLE
The wolf, and ocelot entity

### ISSUE THREAD

**Issue by Aladachoco** [0TeamDev0/Wild-Mobs#4]
So I did some testing and found out the reason to my private server crashing is due to a confusion in the console regarding the wolf, and ocelot entity

Hear me out on this one. so as you know the Wild mobs mod adds a new texture to the Wolf, and Ocelot entity when tamed, but the server is not recognizing this change causing a confusion in the system between the original Minecraft Wolf and Ocelot, and the Wild mobs textured Wolf and Ocelot.......

Any ideas on fixing this bug?

**Comment by DracoScythem** [comment]
From a technical standpoint no textures are actually added to vanilla mobs (while possible, in this case doing so would require some rather dangerous asm hackery), instead WM adds custom derivatives of vanilla wolves and ocelots - those derivatives, are entirely seperate entities, with seperate registry entries, so the server can't actually "confuse them".
What _could_ be happening is something using "wrong" identifiers to distinguish entities (internal names instead of registry names, instanceof instead of class equity checks, etc.), although that's hard to tell without further details.

Could you please post a full crash report (via gist/pastebin/...), including a list of all mods/plugins on the server (should be included in the crash report by default, just make sure it's complete)?

**Comment by DracoScythem** [comment]
Info not provided - closing this issue for now.

**Comment by DracoScythem** [comment]
Possibly related to https://github.com/DracoScythem/Wild-Mobs-1.7.10/commit/1680a92062f9e7db583bc3d1cd3a7363b43053a1 ?
If so, it was resolved in version [1.5.3](https://github.com/DracoScythem/Wild-Mobs-1.7.10/releases/tag/1.5.3).
